<style>
a:visited {
	font-size: 9pt; cursor: hand; color: green; font-family: "verdana", "arial", "helvetica", "sans-serif"; text-decoration: none
}
a:hover {
	font-size: 9pt; cursor: hand; color: red; font-family: "verdana", "arial", "helvetica", "sans-serif"; text-decoration: none
}
a:link {
	font-size: 9pt; cursor: hand; color: green; font-family: "verdana", "arial", "helvetica", "sans-serif"; text-decoration: none
}
td {
	font-size: 9pt; color: #333333;
}
input {
	Font-family:Verdana, Arial, Helvetica, Sans-serif,宋体; Text-decoration: None; Border-top-width: 1px; Border-left-width: 1px; Font-size: 12px; Border-bottom-width: 1px; Border-right-width: 1px;background:#DEF3CE
}
select {
	Font-family:Verdana, Arial, Helvetica, Sans-serif,宋体; Text-decoration: None; Border-top-width: 1px; Border-left-width: 1px; Font-size: 12px; Border-bottom-width: 1px; Border-right-width: 1px;background:#E4EDFB
}
iframe {
	Font-family:Verdana, Arial, Helvetica, Sans-serif,宋体; Text-decoration: None; Border-top-width: 1px; Border-left-width: 1px; Font-size: 12px; Border-bottom-width: 1px; Border-right-width: 1px
}
textarea {
	Font-family:Verdana, Arial, Helvetica, Sans-serif,宋体; Text-decoration: None; Border-top-width: 1px; Border-left-width: 1px; Font-size: 12px; Border-bottom-width: 1px; Border-right-width: 1px;background:#E4EDFB
}

.{
	font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
	font-size: 11px;
	white-space: wrap;
}

table   {border:#DEF3CE solid 1px;}
</style>